### PR TITLE
Remove editorconfig

### PR DESCRIPTION
**Pull request by eirnym**

### CODE REVIEW

**Comment by eirnym** [comment]
@boozook could you please merge this PR?

**Comment by boozook** [comment]
@eirnym, thanks for awesome contribution 👍

According to #235, where you've told:
> Otherwise contributing could be painful
> ...
> EditorConfig would be useful though to make editors format in more or less the same way (at least what's about the tabs and spaces)

So my question is - 
Could you describe your reasons to delete it now?

**Comment by eirnym** [comment]
As you mentioned, it's not possible to include all formatting into this file and `rustfmt` won't support this file any time soon. 

Additionally, even this file supports very basic rules common to every editor for Rust code, it doesn't include any rules for other file types and could potentially lead to inconsistency as `root=true` is present. If it wasn't present, more inconsistency could be introduced. 

Thus, it's better to have either all used types included, or file is not included at all.

**Review by boozook — APPROVED** [review]
Thanks for explanation. LGTM 👍

**Pull request merged**
